before_script:
  - . /etc/profile.d/modules.sh

stages:
  - build
  - verify 
  - deploy

build-TEcode_gcc-openblas:
  stage: build
  script: 
    - ".gitlab-ci/build/build_nscouette.sh TE_CODE gcc-openblas DEBUGyes"
    -  sed -e 's/m_r\s*=\s*\([0-9]\+\)/m_r = 27/' -e  's/m_th\s*=\s*\([0-9]\+\)/m_th = 16/' -e 's/m_z0\s*=\s*\([0-9]\+\)/m_z0 = 32/' -e 's/numsteps\s*=\s*\([0-9]\+\)/numsteps = 200/' -e 's/dn_hdf5\s*=\s*\([0-9]\+\)/dn_hdf5 = 100/' input_nsCouette > input_nsCouette.test_short 
    - .gitlab-ci/test/run_nscouette.sh gcc-openblas 3 2
    - .gitlab-ci/test/run_coverage.sh gcc-openblas coverage_data_TE
  artifacts:
    paths:
    - coverage_data_TE

build-STDcode_gcc-openblas:
  stage: build
  script: 
    - ".gitlab-ci/build/build_nscouette.sh STD_CODE gcc-openblas DEBUGyes"
    -  sed -e 's/m_r\s*=\s*\([0-9]\+\)/m_r = 27/' -e  's/m_th\s*=\s*\([0-9]\+\)/m_th = 16/' -e 's/m_z0\s*=\s*\([0-9]\+\)/m_z0 = 32/' -e 's/numsteps\s*=\s*\([0-9]\+\)/numsteps = 200/' -e 's/dn_hdf5\s*=\s*\([0-9]\+\)/dn_hdf5 = 100/' input_nsCouette > input_nsCouette.test_short 
    - .gitlab-ci/test/run_nscouette.sh gcc-openblas 3 2
    - .gitlab-ci/test/run_coverage.sh gcc-openblas coverage_data_STD
  artifacts:
    paths:
    - coverage_data_STD
 

build-TEcode_intel-mkl:
  stage: build
  script: 
    - ".gitlab-ci/build/build_nscouette.sh TE_CODE intel-mkl DEBUGyes"
    -  sed -e 's/m_r\s*=\s*\([0-9]\+\)/m_r = 27/' -e  's/m_th\s*=\s*\([0-9]\+\)/m_th = 16/' -e 's/m_z0\s*=\s*\([0-9]\+\)/m_z0 = 32/' -e 's/numsteps\s*=\s*\([0-9]\+\)/numsteps = 200/' -e 's/dn_hdf5\s*=\s*\([0-9]\+\)/dn_hdf5 = 100/' input_nsCouette > input_nsCouette.test_short 
    - .gitlab-ci/test/run_nscouette.sh intel-mkl 3 2


build-STDcode_intel-mkl:
  stage: build
  script: 
    - ".gitlab-ci/build/build_nscouette.sh STD_CODE intel-mkl DEBUGyes"
    -  sed -e 's/m_r\s*=\s*\([0-9]\+\)/m_r = 32/' -e  's/m_th\s*=\s*\([0-9]\+\)/m_th = 16/' -e 's/m_z0\s*=\s*\([0-9]\+\)/m_z0 = 32/' -e 's/numsteps\s*=\s*\([0-9]\+\)/numsteps = 200/' -e 's/dn_hdf5\s*=\s*\([0-9]\+\)/dn_hdf5 = 100/' input_nsCouette > input_nsCouette.test_short 
    - .gitlab-ci/test/run_nscouette.sh intel-mkl 4 2

staticcheck-TEcode:
  stage: build
  script: 
     - module load hdf5-mpi intel/16.0 mkl/11.3 impi/5.0.3 forcheck/14.6.26
     - make CODE=TE_CODE HDF5IO=no forcheck

staticcheck-STDcode:
  stage: build
  script: 
     - module load hdf5-mpi intel/16.0 mkl/11.3 impi/5.0.3 forcheck/14.6.26
     - make CODE=STD_CODE HDF5IO=no forcheck


build-ford:
  stage: build
  script:
    - module load python27/python/2.7 intel/16.0 mkl/11.3
    - export PYTHONPATH=/usr/local/lib/python2.7/site-packages/
    - make CODE=TE_CODE HDF5IO=no ford 
  artifacts:
    paths:
    - ford-doc

verify-STDcode_intel-mkl:
  stage: verify
  script: 
    - .gitlab-ci/build/build_nscouette.sh STD_CODE intel-mkl
    - .gitlab-ci/test/verify_nscouette.sh intel-mkl 4 2 reference_run_1
  artifacts:
    paths:
    - environment
    - nscouette.out
    - torque
  only: 

verify-TEcode_intel-mkl:
  stage: verify
  script: 
    - .gitlab-ci/build/build_nscouette.sh TE_CODE intel-mkl
    - .gitlab-ci/test/verify_nscouette.sh intel-mkl 4 2 reference_run_2
  artifacts:
    paths:
    - environment
    - nscouette.out
    - torque
    - Nusselt
  only: 

compareMPI-TEcode_intel-mkl:
  stage: verify
  script: 
    - .gitlab-ci/build/build_nscouette.sh TE_CODE intel-mkl
    -  sed -e 's/m_r\s*=\s*\([0-9]\+\)/m_r = 16/' -e  's/m_th\s*=\s*\([0-9]\+\)/m_th = 24/' -e 's/m_z0\s*=\s*\([0-9]\+\)/m_z0 = 18/' -e 's/numsteps\s*=\s*\([0-9]\+\)/numsteps = 200/' -e 's/dn_hdf5\s*=\s*\([0-9]\+\)/dn_hdf5 = 100/' input_nsCouette > input_nsCouette.test_short 
    - .gitlab-ci/test/run_compare.sh intel-mkl 4 2 8 1
  only: 

validate-STDcode_intel-mkl:
  stage: verify
  script: 
    - .gitlab-ci/test/validate_nscouette.sh intel-mkl 4 2 
  artifacts:
    paths:
    - environment
    - nscouette.out
    - wavespeed.out
    - parameter
  only: 
 
pages:
  stage: deploy
  dependencies:
    - build-TEcode_gcc-openblas
    - build-ford
  script:
    - mv coverage_data_TE/ public/
    - mv ford-doc/ public/
  artifacts:
    paths:
      - public
    expire_in: 60 days
